### ISSUE TITLE
Loging in with facebook doesn't work

### ISSUE THREAD

**Issue by Sakrecoer** [doxel/doxel-viewer#28]
Tryin to log in with Facebook auth gives the following error message:

```App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.```

As seen in the attached image:

![screen shot 2018-08-09 at 13 40 12](https://user-images.githubusercontent.com/3484593/43896699-03674e78-9bda-11e8-8ce9-097a4947f475.png)

**Comment by luxigo** [comment]
It's a doxel-loopback issue, there is no authentication handling at the doxel-viewer level.

Since August 2nd, the Facebook policy changed and requires specifying a privacy policy url and switching to production mode in order to allow logins using Facebook account because it exposes the e-mail address of the Facebook user. 

I am not a lawyer I do not have a suitable privacy policy model handy despite I asked one to whom it may concern , so I could not make it on time.

**Comment by Sakrecoer** [comment]
facebook is over
